server:
  port: 8081
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 39.105.71.94 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 1000 # 连接超时时间（毫秒）
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.cute.community.entity
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
jwt:
  secret: community
  expiration: 1296000
  tokenStart: "Bearer"
  tokenName: Authorization
  defaultPassword: "123456"
img:
  location: D:\\photo\\
  url: http://baobao.mynatapp.cc/
